# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NIBMArticle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Nuke','~>7.0'
  pod 'BiometricAuthentication'
  # Pods for NIBMArticle

  target 'NIBMArticleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NIBMArticleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
